name: Java CI

on:
  push:
    branches:
      - main
      - steve
  pull_request:
    branches:
      - main
      - steve

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21 with Temurin
        uses: actions/setup-java@v3
        with:
          java-version: '21'            # Specify the Java version
          distribution: 'temurin'       # Specify the JDK distribution (Temurin)

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Docker Image
        run: docker build -t sew_styles_backend .

      - name: Verify Docker Installation
        run: docker --version  # Verify Docker is installed and accessible

      - name: Push Docker Image to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "Username: $DOCKER_USERNAME"  # Ensure username is correct
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker tag sew_styles_backend otizaaa/sew_styles_backend:latest
          docker push otizaaa/sew_styles_backend:latest


